name: Do RSpec Test
on: [push]
jobs:
  RSpec-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true
      - name: Bundler ang Gem Install
        run: |
          gem install bundler
          bundle install
      - name: Create and Migrate Database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILE_ENV=test
          bundle exec rails db:environment:set RAILS_ENV=test
      - name: Run Tests
        run: bundle exec rspec
